// Indian States and Union Territories (Maharashtra focus)
export const INDIAN_STATES = [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  // Union Territories
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
];

// Major cities in Maharashtra (primary operating region)
export const MAHARASHTRA_CITIES = [
  'Mumbai',
  'Pune',
  'Nagpur',
  'Thane',
  'Nashik',
  'Aurangabad (Sambhajinagar)',
  'Solapur',
  'Kolhapur',
  'Amravati',
  'Navi Mumbai',
  'Sangli',
  'Akola',
  'Jalgaon',
  'Latur',
  'Dhule',
  'Nanded',
  'Ahmednagar',
  'Chandrapur',
  'Parbhani',
  'Satara',
  'Ratnagiri',
  'Panvel',
];
